version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: sankofa
      POSTGRES_PASSWORD: sankofa123
      POSTGRES_DB: sankofa_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
